flipcard/bottom nav issue
LearningPool/adapt-contrib-flipcard pull request #30
Opened 2019-02-08 16:47 UTC by warwickandrew

fixes jumping movement when flipcard and footer nav is used together

2019-02-19 11:48 UTC, nilslp commented on less/flipcard.less
> +      flipcard-item-face {
Can you double check that this is actually correct.
Looks like the `.` for the class is missing here.

2019-02-19 11:49 UTC, nilslp requested changes
Could you take a look at the comment I left please.
Then bump the version of the plugin, Thanks

2019-03-04 12:43 UTC, cahirodoherty-learningpool requested changes

2019-03-04 12:43 UTC, cahirodoherty-learningpool commented on bower.json
> +    "repository": "git://github.com/ExultCorp/adapt-contrib-flipcard.git",
These changes should not have been reintroduced

2019-03-04 12:43 UTC, cahirodoherty-learningpool commented on less/flipcard.less
>        width: 100%;
Should this be 99% I think a merge conflict resolution has made this creep in

2019-03-04 16:44 UTC, cahirodoherty-learningpool approved these changes

2019-03-05 09:37 UTC, danielstorey approved these changes

2019-03-05 11:18 UTC, nilslp approved these changes

2019-03-19 09:21 UTC, merged